language: java
jdk:
 - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - sudo add-apt-repository --yes ppa:nginx/stable
  - sudo apt-get update -q
  - sudo apt-get install nginx
  - sudo add-apt-repository --yes ppa:chris-lea/zeromq
  - sudo apt-get update
  - sudo apt-get install libzmq3-dbg libzmq3-dev libzmq3
  - sudo apt-get install python-pip python-dev
  - sudo pip install ipython jinja2 tornado
  - sudo pip install pyzmq
  - sudo apt-get install python-matplotlib python-scipy python-pandas
  - sudo add-apt-repository --yes ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install r-base r-base-dev
